version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    restart: always
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      SMTP_HOST:
      SMTP_PORT:
      SMTP_USERNAME:
      SMTP_PASSWORD:
      MYSQL_DB: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_URL: 'db'

volumes:
  my-db: